# Generated by Django 3.1.1 on 2020-10-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('msg_body', models.TextField(verbose_name='留言内容')),
                ('msg_user', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='留言用户')),
            ],
            options={
                'db_table': 'message_list',
                'ordering': ('-id',),
            },
        ),
    ]
