# Generated by Django 3.1.1 on 2020-10-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=128, verbose_name='作品标题')),
                ('work_description', models.TextField(verbose_name='作品简介')),
                ('work_created_time', models.DateTimeField(auto_now_add=True, verbose_name='作品发布时间')),
                ('work_img', models.ImageField(blank=True, upload_to='work_show/<django.db.models.fields.related.ForeignKey>/', verbose_name='作品图片')),
                ('work_label', models.IntegerField(choices=[(1, 'Python'), (2, 'Java'), (3, '其他编程'), (4, '摄影'), (5, '3D打印'), (6, '激光雕刻'), (0, '其他')], verbose_name='作品标签')),
                ('work_author', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='创作者')),
            ],
            options={
                'db_table': 'work_show',
                'ordering': ('-work_created_time',),
            },
        ),
    ]
