# Generated by Django 3.1.1 on 2020-10-20 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('art_body', models.TextField(help_text='建议使用 markdown 语法', verbose_name='文章正文')),
                ('art_created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='文章创建时间')),
                ('art_updated_time', models.DateTimeField(auto_now=True, verbose_name='上一次编辑时间')),
                ('article_img', models.ImageField(blank=True, upload_to='article/<django.db.models.fields.related.ForeignKey>/', verbose_name='文章图片')),
                ('article_label', models.IntegerField(choices=[(0, '未分组'), (1, 'Python'), (2, '计算机/编程'), (3, '摄影'), (4, '其他技术类'), (5, '随笔'), (6, '其他')], verbose_name='文章标签')),
                ('art_author', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='文章作者')),
            ],
            options={
                'db_table': 'article',
                'ordering': ('-id',),
            },
        ),
    ]
