# Generated by Django 3.1.1 on 2020-10-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(max_length=128, verbose_name='活动标题')),
                ('act_details', models.TextField(verbose_name='活动详情')),
                ('act_created_time', models.DateTimeField(auto_now_add=True, verbose_name='活动发起时间')),
                ('act_time', models.DateTimeField(verbose_name='活动时间')),
                ('act_img', models.ImageField(blank=True, upload_to='schedule/%Y%m/', verbose_name='活动图片')),
                ('act_sponsor', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='发起人')),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ('-id',),
            },
        ),
    ]
