# Generated by Django 3.1.1 on 2020-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('student_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='学号')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('qq', models.CharField(blank=True, max_length=32, verbose_name='QQ')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user_img', models.ImageField(blank=True, upload_to='userprofile/', verbose_name='用户头像')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
